# Generated by Django 5.0.1 on 2024-01-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=85)),
                ("content", models.CharField(max_length=300)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
